import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { SettingsResponse } from "../api/client";
import "./SettingsPanel.css";

// Model provider + word-weighting are server-side, global (single-user, no
// auth) settings - not a per-viewer preference like the voice picker, so
// they're read from and written straight to the backend (GET/PUT
// /settings) rather than localStorage.
export function SettingsPanel() {
  const [settings, setSettings] = useState<SettingsResponse | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api
      .getSettings()
      .then(setSettings)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)));
  }, []);

  const apply = (patch: { model_provider?: string; word_weighting_enabled?: boolean }) => {
    setSaving(true);
    setError(null);
    api
      .updateSettings(patch)
      .then(setSettings)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)))
      .finally(() => setSaving(false));
  };

  // Nothing to show until the initial load resolves - this is a secondary
  // control, not core chat functionality, so there's no loading spinner
  // here; it just pops in a beat after the rest of the header.
  if (!settings) return null;

  const isLocal = settings.model_provider === "local";

  return (
    <div className="settings-panel">
      <label className="settings-panel__field" title="Which chat backend replies are generated by">
        Model:{" "}
        <select
          value={settings.model_provider}
          disabled={saving}
          onChange={(e) => apply({ model_provider: e.target.value })}
        >
          <option value="local">Local</option>
          <option value="openai">Hosted (API)</option>
        </select>
      </label>
      <label
        className="settings-panel__field"
        title={
          isLocal
            ? "Nudges replies toward words you're due to review"
            : "Needs the local model's own tokenizer - not available with the hosted backend"
        }
      >
        <input
          type="checkbox"
          checked={settings.word_weighting_enabled}
          disabled={saving || !isLocal}
          onChange={(e) => apply({ word_weighting_enabled: e.target.checked })}
        />{" "}
        Word weighting
      </label>
      {error && <span className="settings-panel__error">{error}</span>}
    </div>
  );
}
