/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_chat_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear History */
        post: operations["clear_history_chat_history_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Turn */
        post: operations["take_turn_chat_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate Text */
        post: operations["translate_text_translate_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret Input
         * @description For the learner's own message: infers what they meant across a
         *     possible mix of English/Spanish and grammar mistakes, returning a
         *     corrected English restatement alongside its Spanish translation - used
         *     to show both under the user's chat bubble rather than a single literal
         *     (and possibly nonsensical) pass.
         */
        post: operations["interpret_input_translate_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coach Draft
         * @description For a message the learner is still drafting (not yet sent) - unlike
         *     /interpret above, which corrects a single message in isolation, this
         *     pulls the session's recent conversation for context so the suggested
         *     phrasing actually fits the tone of what's been said so far, and returns
         *     feedback on the attempt plus phrasing options at a few formality
         *     levels rather than a single flat correction.
         */
        post: operations["coach_draft_translate_coach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/tag-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tag Input
         * @description Two independent passes over the same draft text: `tokens` is a
         *     cheap, synchronous, LLM-free per-word classification (spaCy +
         *     lemmatizer.py's is_spanish heuristic) the frontend needs on every call
         *     for reward-event tracking and its phrase-selection direction vote;
         *     `spans` is the slower LLM-backed word/group glossing (app.translate.
         *     llm_translate.tag_draft) that drives the hover-to-translate UI,
         *     matched back to exact offsets via app.translate.span_matching. Kept in
         *     one response so the frontend only has one request to debounce, even
         *     though the two halves serve different purposes. On an LLM failure,
         *     `spans` comes back empty - no dictionary/MT fallback - but `tokens` is
         *     unaffected.
         */
        post: operations["tag_input_translate_tag_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reward Event */
        post: operations["reward_event_events_reward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_tts_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speak */
        post: operations["speak_tts_speak_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_settings_get"];
        /** Write Settings */
        put: operations["write_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Llm
         * @description Whether the active chat backend can actually serve a completion
         *     right now - distinct from /health above, which only means this process
         *     is up. Under the "openai" provider there's no self-hosted model server
         *     to wait on at all - ready as soon as a key is configured to call it
         *     with, no cold-start wait to gate the UI on. Under "local" (the
         *     default): model-server runs with Railway's serverless mode (sleeps
         *     after ~5-10min idle) and, right after a cold start, spends a stretch
         *     loading the model's weights into memory before its own /health reports
         *     ready - either way, a chat/translate request that lands during that
         *     window fails with llama_client.ModelServerUnavailableError. Hitting it
         *     here (rather than trusting a cached flag) is itself the wake-up
         *     trigger for the sleep case - Railway wakes a serverless service on any
         *     inbound request. The frontend is expected to poll this on page load
         *     and hold the UI back until it reports ready, rather than let a real
         *     interaction be the first thing to hit that failure mode.
         */
        get: operations["health_llm_health_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatHistoryMessage */
        ChatHistoryMessage: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Tokens
             * @default []
             */
            tokens: components["schemas"]["TokenAnnotation"][];
        };
        /** ChatHistoryResponse */
        ChatHistoryResponse: {
            /** Messages */
            messages: components["schemas"]["ChatHistoryMessage"][];
        };
        /** ChatTurnRequest */
        ChatTurnRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
        };
        /** ChatTurnResponse */
        ChatTurnResponse: {
            /** Message Id */
            message_id: number;
            /** Text */
            text: string;
            /** Tokens */
            tokens: components["schemas"]["TokenAnnotation"][];
            /**
             * Translation
             * @default
             */
            translation: string;
        };
        /** ClearHistoryResponse */
        ClearHistoryResponse: {
            /** Cleared */
            cleared: number;
        };
        /** CoachDraftRequest */
        CoachDraftRequest: {
            /** Text */
            text: string;
            /** Session Id */
            session_id: string;
        };
        /** CoachDraftResponse */
        CoachDraftResponse: {
            /** Meaning */
            meaning: string;
            /** Feedback */
            feedback: string;
            /** Options */
            options: components["schemas"]["CoachOption"][];
        };
        /** CoachOption */
        CoachOption: {
            /** Formality */
            formality: string;
            /** Spanish */
            spanish: string;
        };
        /** DraftSpan */
        DraftSpan: {
            /** Surface */
            surface: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Clickable */
            clickable: boolean;
            /** Candidates */
            candidates: components["schemas"]["TranslateCandidate"][];
        };
        /** DraftToken */
        DraftToken: {
            /** Surface */
            surface: string;
            /** Lemma */
            lemma: string;
            /** Is Spanish */
            is_spanish: boolean;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterpretInputRequest */
        InterpretInputRequest: {
            /** Text */
            text: string;
        };
        /** InterpretInputResponse */
        InterpretInputResponse: {
            /** Native */
            native: string;
            /** Target */
            target: string;
        };
        /** LlmHealthResponse */
        LlmHealthResponse: {
            /** Ready */
            ready: boolean;
        };
        /** RewardEventRequest */
        RewardEventRequest: {
            /** Event Type */
            event_type: string;
            /** Lemma */
            lemma: string;
        };
        /** RewardEventResponse */
        RewardEventResponse: {
            /** Lemma */
            lemma: string;
            /** Familiarity */
            familiarity: number;
            /** Review Interval Days */
            review_interval_days: number;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Model Provider */
            model_provider: string;
            /** Word Weighting Enabled */
            word_weighting_enabled: boolean;
            /** Word Weighting Active */
            word_weighting_active: boolean;
        };
        /** TTSRequest */
        TTSRequest: {
            /** Text */
            text: string;
            /**
             * Language
             * @default es
             */
            language: string;
            /** Voice */
            voice?: string | null;
        };
        /** TTSVoicesResponse */
        TTSVoicesResponse: {
            /** Voices */
            voices: string[];
            /** Default */
            default: string;
        };
        /** TagInputRequest */
        TagInputRequest: {
            /** Text */
            text: string;
        };
        /** TagInputResponse */
        TagInputResponse: {
            /** Tokens */
            tokens: components["schemas"]["DraftToken"][];
            /** Spans */
            spans: components["schemas"]["DraftSpan"][];
        };
        /** TokenAnnotation */
        TokenAnnotation: {
            /** Surface */
            surface: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Gloss */
            gloss: string;
            /** Is New */
            is_new: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** TranslateCandidate */
        TranslateCandidate: {
            /** Translation */
            translation: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** TranslateTextRequest */
        TranslateTextRequest: {
            /** Text */
            text: string;
            /**
             * Source Lang
             * @default es
             */
            source_lang: string;
            /**
             * Target Lang
             * @default en
             */
            target_lang: string;
        };
        /** TranslateTextResponse */
        TranslateTextResponse: {
            /** Translation */
            translation: string;
        };
        /** UpdateSettingsRequest */
        UpdateSettingsRequest: {
            /** Model Provider */
            model_provider?: string | null;
            /** Word Weighting Enabled */
            word_weighting_enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_history_chat_history_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_chat_history_clear_post: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_chat_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_text_translate_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_input_translate_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_draft_translate_coach_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tag_input_translate_tag_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reward_event_events_reward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewardEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_tts_voices_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTSVoicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speak_tts_speak_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TTSRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    write_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_llm_health_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmHealthResponse"];
                };
            };
        };
    };
}
