/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_chat_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear History */
        post: operations["clear_history_chat_history_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Turn */
        post: operations["take_turn_chat_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/turn/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Turn Stream
         * @description Same turn as POST /chat/turn, but the model's reply streams to the
         *     client as it's generated instead of waiting for the whole thing - for a
         *     live, typing-style display. Streamed as Server-Sent Events: a "chunk"
         *     event per token/delta of the reply's own text, then (once generation
         *     finishes) the exact same gloss/translate/persist work /chat/turn does,
         *     sent as one final "done" event carrying the exact same ChatTurnResponse
         *     shape /chat/turn returns - so the frontend ends up with one consistent
         *     payload either way, just delivered progressively here.
         */
        post: operations["take_turn_stream_chat_turn_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translate Text */
        post: operations["translate_text_translate_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret Input
         * @description For the learner's own message: infers what they meant across a
         *     possible mix of English/Spanish and grammar mistakes, returning a
         *     corrected English restatement alongside its Spanish translation - used
         *     to show both under the user's chat bubble rather than a single literal
         *     (and possibly nonsensical) pass.
         */
        post: operations["interpret_input_translate_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coach Draft
         * @description For a message the learner is still drafting (not yet sent) - unlike
         *     /interpret above, which corrects a single message in isolation, this
         *     pulls the session's recent conversation for context so the suggested
         *     phrasing actually fits the tone of what's been said so far, and returns
         *     feedback on the attempt plus phrasing options at a few formality
         *     levels rather than a single flat correction.
         *
         *     Streamed as Server-Sent Events, one event per phase of the SAME
         *     underlying LLM call (app.translate.llm_translate.coach_draft_stream):
         *     a "core" event the moment the feedback + options themselves are ready
         *     (usable immediately - the frontend shows these without waiting on
         *     anything else), then a "translations" event once each option's own
         *     English translation + word-by-word breakdown finishes streaming
         *     afterward (for pre-populating the chat input's gloss cache the instant
         *     an option is picked - see CoachOption's fields). An "error" event
         *     means the core phase itself never produced anything usable; a stream
         *     that ends after "core" with no "translations" just means that part
         *     wasn't ready - that's not itself an error (see coach_draft_stream's
         *     docstring).
         */
        post: operations["coach_draft_translate_coach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/tag-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tag Input
         * @description Cheap, synchronous, LLM-free per-word classification (spaCy +
         *     lemmatizer.py's is_spanish heuristic) - fast enough to call on every
         *     keystroke (debounced). Needed for reward-event tracking
         *     (userTypedSpanishWord) and the phrase-selection direction vote. The
         *     slower LLM-backed word/group glossing that drives the hover-to-
         *     translate UI lives separately in /translate/gloss-spans below, fetched
         *     lazily on interaction rather than on every edit.
         */
        post: operations["tag_input_translate_tag_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/gloss-spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gloss Spans
         * @description The slower, LLM-backed half of what used to be /translate/tag-input:
         *     app.translate.llm_translate.tag_draft's word/group glossing, matched
         *     back to exact offsets via app.translate.span_matching. Fetched lazily
         *     (on hover/click/tap of a word), not on every keystroke, since this is a
         *     real LLM call. On failure, returns an empty span list - no dictionary/
         *     MT fallback.
         */
        post: operations["gloss_spans_translate_gloss_spans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reward Event */
        post: operations["reward_event_events_reward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_tts_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speak */
        post: operations["speak_tts_speak_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Llm
         * @description Whether the chat backend (OpenAI) is actually configured and able to
         *     serve a completion right now - distinct from /health above, which only
         *     means this process is up. Ready as soon as a key is configured; the
         *     frontend polls this on page load and holds the UI back until it reports
         *     ready, which is also what wakes Railway's own serverless sleep on the
         *     backend process itself, if it's asleep.
         */
        get: operations["health_llm_health_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatHistoryMessage */
        ChatHistoryMessage: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Tokens
             * @default []
             */
            tokens: components["schemas"]["TokenAnnotation"][];
        };
        /** ChatHistoryResponse */
        ChatHistoryResponse: {
            /** Messages */
            messages: components["schemas"]["ChatHistoryMessage"][];
        };
        /** ChatTurnRequest */
        ChatTurnRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
        };
        /** ChatTurnResponse */
        ChatTurnResponse: {
            /** Message Id */
            message_id: number;
            /** Text */
            text: string;
            /** Tokens */
            tokens: components["schemas"]["TokenAnnotation"][];
            /**
             * Translation
             * @default
             */
            translation: string;
        };
        /** ClearHistoryResponse */
        ClearHistoryResponse: {
            /** Cleared */
            cleared: number;
        };
        /** CoachDraftRequest */
        CoachDraftRequest: {
            /** Text */
            text: string;
            /** Session Id */
            session_id: string;
        };
        /** DraftSpan */
        DraftSpan: {
            /** Surface */
            surface: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Clickable */
            clickable: boolean;
            /** Candidates */
            candidates: components["schemas"]["TranslateCandidate"][];
            /**
             * Alternate Gloss
             * @default
             */
            alternate_gloss: string;
            /**
             * Literal
             * @default
             */
            literal: string;
        };
        /** DraftToken */
        DraftToken: {
            /** Surface */
            surface: string;
            /** Lemma */
            lemma: string;
            /** Is Spanish */
            is_spanish: boolean;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** GlossSpansRequest */
        GlossSpansRequest: {
            /** Text */
            text: string;
        };
        /** GlossSpansResponse */
        GlossSpansResponse: {
            /** Spans */
            spans: components["schemas"]["DraftSpan"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterpretInputRequest */
        InterpretInputRequest: {
            /** Text */
            text: string;
        };
        /** InterpretInputResponse */
        InterpretInputResponse: {
            /** Native */
            native: string;
            /** Target */
            target: string;
        };
        /** LlmHealthResponse */
        LlmHealthResponse: {
            /** Ready */
            ready: boolean;
        };
        /** RewardEventRequest */
        RewardEventRequest: {
            /** Event Type */
            event_type: string;
            /** Lemma */
            lemma: string;
        };
        /** RewardEventResponse */
        RewardEventResponse: {
            /** Lemma */
            lemma: string;
            /** Familiarity */
            familiarity: number;
            /** Review Interval Days */
            review_interval_days: number;
        };
        /** TTSRequest */
        TTSRequest: {
            /** Text */
            text: string;
            /**
             * Language
             * @default es
             */
            language: string;
            /** Voice */
            voice?: string | null;
        };
        /** TTSVoicesResponse */
        TTSVoicesResponse: {
            /** Voices */
            voices: string[];
            /** Default */
            default: string;
        };
        /** TagInputRequest */
        TagInputRequest: {
            /** Text */
            text: string;
        };
        /** TagInputResponse */
        TagInputResponse: {
            /** Tokens */
            tokens: components["schemas"]["DraftToken"][];
        };
        /** TokenAnnotation */
        TokenAnnotation: {
            /** Surface */
            surface: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Gloss */
            gloss: string;
            /** Is New */
            is_new: boolean;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Literal
             * @default
             */
            literal: string;
        };
        /** TranslateCandidate */
        TranslateCandidate: {
            /** Translation */
            translation: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** TranslateTextRequest */
        TranslateTextRequest: {
            /** Text */
            text: string;
            /**
             * Source Lang
             * @default es
             */
            source_lang: string;
            /**
             * Target Lang
             * @default en
             */
            target_lang: string;
        };
        /** TranslateTextResponse */
        TranslateTextResponse: {
            /** Translation */
            translation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_history_chat_history_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_chat_history_clear_post: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_chat_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_stream_chat_turn_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_text_translate_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_input_translate_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_draft_translate_coach_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tag_input_translate_tag_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gloss_spans_translate_gloss_spans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossSpansRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossSpansResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reward_event_events_reward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewardEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_tts_voices_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTSVoicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speak_tts_speak_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TTSRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_llm_health_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmHealthResponse"];
                };
            };
        };
    };
}
